---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: fill
    theme: cosmo                                                                                            
---


```{r dashboard, include=FALSE}

library(flexdashboard)
library(tidyverse)
library(rvest)
library(httr)
library(plotly)
library(rgdal)
library(patchwork)
library(readr)
library(ggplot2)
library(readxl)
theme_set(theme_bw())
```

```{r tidy,include= FALSE}
mydat = rgdal::readOGR("./UHF42/UHF_42_DOHMH.shp")
map_data = fortify(mydat) %>%
  dplyr::select(id, everything() )%>%
  nest(long:group)
map_data$uhf = mydat$UHFCODE
map_data = map_data %>%
  unnest %>%
  dplyr::select(-id) %>%
  dplyr::select(id = uhf, everything()) %>%
  dplyr::select(long, lat, everything())

names(map_data)[1:2] = c("x","y") 

asthma_air = read_csv("./data/asthma_air/Data.csv") %>%
  filter(str_detect(year_description, "^20|^An")) %>%
  mutate(year_description = str_remove(year_description, "Annual Average ")) %>%
    filter(year_description == 2015)

sulfur_dioxide= read_csv("./data/asthma_air/Data.csv") %>%
  filter(name == "Sulfur Dioxide (SO2)") %>%
  filter(year_description == "Winter 2014-15")

ozone= read_csv("./data/asthma_air/Data.csv") %>%
  filter(name == "Ozone (O3)") %>%
  filter(year_description == "Summer 2015")

poverty= read_csv("./data/poverty/Data.csv") %>%
  filter(year_description == "2011-15" )

data = rbind(asthma_air,sulfur_dioxide,ozone, poverty)
  
asthma_air1 = data %>%
  dplyr::select(name, description, Measure, geo_entity_name, geo_entity_id, year = year_description, data_value) %>%
  janitor::clean_names() %>% 
  filter(measure %in% c("Mean", "Rate", "Number", "Percent", "Age-Adjusted Percent", "Age-Adjusted Rate ")) %>%
  mutate(name_measure=str_c(name,"-",measure)) %>%
  dplyr::select(-name, -measure, -description, -year) %>%
  spread(key = name_measure, value = data_value) %>%
  janitor::clean_names()

asthma_map = asthma_air1 %>%
  dplyr::select (id = geo_entity_id, asthma = asthma_emergency_department_visits_children_0_to_4_yrs_old_rate)
asthma_air = read_csv("./data/asthma_air/Data.csv") %>%
  filter(str_detect(year_description, "^20|^An")) %>%
  mutate(year_description = str_remove(year_description, "Annual Average "))

```

```{r tree_tidy,include = F}
#import and tidy tree data
tree_df = read_csv("./data/2015StreetTreesCensus_TREES.csv") %>%
  janitor::clean_names() %>%
  filter(status == "Alive")

zipcode_uhf42 = read_excel("./data/Zipcode_UHF42.xlsx") %>%
   gather(key = zipcode_no, value = zipcode, zipcode1:zipcode9) %>%
   dplyr::select(-zipcode_no, uhf42_name) %>%
   filter(is.na(zipcode) == FALSE)

tree_df = left_join(tree_df, zipcode_uhf42, by = "zipcode") 

mydat = rgdal::readOGR("./UHF42/UHF_42_DOHMH.shp")

area=data.frame(uhf42_code = mydat$UHFCODE,area = mydat$SHAPE_Area) %>%
  filter(is.na(uhf42_code) == FALSE)

tree_df = left_join(tree_df, area, by = "uhf42_code")
#tree density
tree_density = tree_df %>%
  group_by(uhf42_name, uhf42_code, area, health) %>%
  dplyr::summarize(health_total = n()) %>%
  filter(is.na(uhf42_name) == FALSE) %>%
  group_by(uhf42_name) %>%
  dplyr::mutate(total = sum(health_total),
                tree_density = total/area,
                health_tree_density = health_total/area) %>%
  ungroup() %>%
  mutate(uhf42_name = forcats::fct_reorder(uhf42_name, tree_density))

asthma_air = read_csv("./data/asthma_air/Data.csv") %>%
  janitor::clean_names()

asthma_em_0to4 = asthma_air %>%
  filter(name == "Asthma Emergency Department Visits (Children 0 to 4 Yrs Old)",
         measure == "Rate",
         year_description == "2015") %>%
  dplyr::select(geo_entity_id, geo_entity_name, asthma_em_0to4 = data_value)

asthma_em_5to14 = asthma_air %>%
  filter(name == "Asthma Emergency Department Visits (Children 5 to 14 Yrs Old)",
         measure == "Rate",
         year_description == "2015") %>%
  dplyr::select(geo_entity_id, asthma_em_5to14 = data_value) 

so2 = asthma_air %>%
  filter(name == "Sulfur Dioxide (SO2)",
         measure == "Mean",
         year_description == "Winter 2014-15") %>%
  dplyr::select(geo_entity_id, so2 = data_value)

poverty = read_csv("./data/poverty/Data.csv") %>%
  janitor::clean_names() %>%
  filter(year_description == "2012-16",
         measure == "Percent",
         name == "Poverty") %>%
  dplyr::select(geo_entity_id, poverty = data_value) 

poverty_under5 = read_csv("./data/poverty/Data.csv") %>%
  janitor::clean_names() %>%
  filter(year_description == "2011-15",
         measure == "Percent",
         name == "Children under 5 years old in Poverty") %>%
  dplyr::select(geo_entity_id, poverty_under5 = data_value) 

tree_density_total = tree_density%>%
  dplyr::select(geo_entity_id=uhf42_code,tree_density) %>%
  distinct()

final_df = left_join(asthma_em_0to4,asthma_em_5to14) %>%
  left_join(so2) %>%
  left_join(poverty) %>%
  left_join(poverty_under5) %>%
  left_join(tree_density_total) %>%
  mutate(asthma_total = asthma_em_0to4+asthma_em_5to14,
         geo_entity_name = forcats::fct_reorder(geo_entity_name, asthma_total)) 
#asthma and so2
final_asthma_df = gather(final_df, key = asthma_age, value = rate, asthma_em_0to4:asthma_em_5to14) %>%
  gather(key = poverty_age, value = poverty, poverty:poverty_under5) %>%
  filter((asthma_age == "asthma_em_5to14"&poverty_age == "poverty")|(asthma_age == "asthma_em_0to4"& poverty_age == "poverty_under5"))
```



Column {.tabset data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
ggplot(asthma_map) +
    geom_map(aes(map_id = id, fill = asthma), color = "white", map = map_data) +
    scale_fill_gradient(high = "darkgreen",low = "lightgreen") +
    expand_limits(map_data)
```


### Chart B

```{r}
ax = list(
  title = "",
  zeroline = FALSE,
  showline = FALSE,
  showticklabels = FALSE,
  showgrid = FALSE
)
#asthma 0-4 and asthma 5-14 in each UHF42
final_asthma_df %>% 
  mutate(asthma_age = str_replace(asthma_age,"asthma_em_","children ")) %>% 
plot_ly(x= ~rate, y= ~geo_entity_name, color = ~asthma_age, type = 'bar', orientation = 'h') %>%
  layout(
         yaxis = ax,
         xaxis = list(title = "rate") 
         
  )
```

Column {data-width=550}
-----------------------------------------------------------------------
### Scatterplot between SO2 and the rate of asthma emergency department visits in different age group children

```{r}
so2_plot = ggplot(final_asthma_df) +
   geom_point(aes(x=so2,y=rate,color=asthma_age))+
   geom_smooth(aes(x=so2,y=rate,color = asthma_age), method = "lm",se=F)+theme(legend.position = "none")
ggplotly(so2_plot)
```


### Scatterplot between poverty and the rate of asthma emergency department visits in different age griup children

```{r}
#asthma and poverty
poverty = ggplot(final_asthma_df) +
   geom_point(aes(x=poverty,y=rate,color=asthma_age))+
   geom_smooth(aes(x=poverty,y=rate,color = asthma_age), method = "lm",se=F)+theme(legend.position = "none")
  ggplotly(poverty)

```




